=== Engeniy/IT-Academy/Homeworks/src/ru/mail/krivonos/al/lesson/twenty/myschema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.it-academy.by"
           xmlns="https://www.it-academy.by"
           elementFormDefault="qualified">
    <xs:element name="category">
        <xs:complexType>
            <xs:all>
                <xs:element name="category_id" type="xs:integer"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="desc" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="stock_daily_record">
        <xs:complexType>
            <xs:all>
                <xs:element name="record_id" type="xs:integer"/>
                <xs:element name="price_open" type="xs:decimal"/>
                <xs:element name="price_close" type="xs:decimal"/>
                <xs:element name="price_change" type="xs:decimal"/>
                <xs:element name="volume" type="xs:long"/>
                <xs:element name="date" type="xs:date"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="stock">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="stock_id" type="xs:integer"/>
                <xs:element name="stock_code" type="xs:string"/>
                <xs:element name="stock_name" type="xs:string"/>
                <xs:element ref="category"/>
                <xs:element ref="stock_daily_records"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="stock_daily_records">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="bucket" maxOccurs="20"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="bucket">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="stock_daily_record" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="set">
            <xs:selector xpath="stock_daily_record"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== Engeniy/IT-Academy/Homeworks/src/ru/mail/krivonos/al/lesson/twenty/myxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<stock xmlns="https://www.it-academy.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://www.it-academy.by myschema.xsd" stock_id="29">
    <stock_code>Def_stock</stock_code>
    <stock_name>Default stock</stock_name>
    <category category_id="10">
        <name>Default category</name>
        <desc>My default category</desc>
    </category>
    <stock_daily_records>
        <bucket>
            <stock_daily_record record_id="27">
                <price_open>26.8</price_open>
                <price_close>30.6</price_close>
                <price_change>2.5</price_change>
                <volume>23456</volume>
                <date>1995-07-03</date>
            </stock_daily_record>
            <stock_daily_record>
                <price_open>78.8</price_open>
                <price_close>39.6</price_close>
                <price_change>29.5</price_change>
                <volume>23466556</volume>
                <date>1995-08-03</date>
            </stock_daily_record>
        </bucket>
        <bucket>
            <stock_daily_record record_id="25">
                <price_open>45.8</price_open>
                <price_close>87.6</price_close>
                <price_change>14.5</price_change>
                <volume>287976</volume>
                <date>1995-07-09</date>
            </stock_daily_record>
            <stock_daily_record record_id="76">
                <price_open>45.8</price_open>
                <price_close>87.6</price_close>
                <price_change>14.5</price_change>
                <volume>287976</volume>
                <date>1995-07-09</date>
            </stock_daily_record>
            <stock_daily_record record_id="77">
                <price_open>45.8</price_open>
                <price_close>87.6</price_close>
                <price_change>14.5</price_change>
                <volume>287976</volume>
                <date>1995-07-09</date>
            </stock_daily_record>
        </bucket>
    </stock_daily_records>
</stock>
